# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rehearsal_dinner',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
        migrations.AddField(
            model_name='party',
            name='language',
            field=models.CharField(choices=[(b'en', b'English'), (b'es', 'Espa\xf1ol'), (b'nl', b'Nederlands')], default='es', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
