# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180629_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='is_invited',
            field=models.BooleanField(default=True),
        ),
    ]
